### ISSUE TITLE
Route 53 - Vinculando domínio na Registro BR e aws

### ISSUE THREAD

**Issue by fernando10092** [fernando10092/Projeto2#1]
Estou com problemas para vincular meu dominio na Route 53 da Amazon. Meu DNS esta na Resgistro BR.

Tentei de varias formas, assisti diversos videos na internet e não consigo vincular meu dominio.

Ele só funciona se eu coloco o seguinte endereço: http://52.67.101.79:3333/index (vocês podem verificar que este caminho funciona no browser de vocês).

Os registros foram criados corretamente na Router 53 de acordo com o video abaixo e varios outros.

Acredito que o problema esteja na passagem de valores como a porta "3333" e o "/index". 

Fiz o procedimento do video abaixo e vários outros e mesmo assim não funciona.
https://www.youtube.com/watch?v=hY4bm4eEUsY

Alguém pode me ajudar ?

**Comment by JuanFontes** [comment]
Oi Fernando, você não consegue apontar um domínio para uma porta específica, DNSs não funcionam assim. Você tem que ir no registro.br e colocar os Nameservers que a AWS te deu do seu domínio lá. Após isso, você precisa os records A/CNAME para a sua instância, basicamente é um` *.` e um `www`. Mas isso ainda não fará você ver seu aplicativo no seu domínio, pois ele vai tentar abrir a porta 80 ou 443. Existem algumas formas pra você conseguir "consertar" isso:

- Colocar um load balancer na frente da sua instancia que aceita conexões na porta 80 e redireciona pra 3333 dessa instancia e configurar ele como um alias dos seus records.
- Mudar sua aplicação pra rodar na porta 80
- Colocar um nginx na sua instancia que  aceite conexões na porta 80 e redirecione pra 3333 dele proprio.


Acho que basicamente existem essas opções, lembre-se que em DNS não se trabalha com porta ou path, para isso você precisa de um servidor web que faça "proxy_pass" e/ou um load balancer, existem diversas formas.

**Comment by JuanFontes** [comment]
@fernando10092

**Comment by fernando10092** [comment]
> Oi Fernando, você não consegue apontar um domínio para uma porta específica, DNSs não funcionam assim. Você tem que ir no registro.br e colocar os Nameservers que a AWS te deu do seu domínio lá. Após isso, você precisa os records A/CNAME para a sua instância, basicamente é um` *.` e um `www`. Mas isso ainda não fará você ver seu aplicativo no seu domínio, pois ele vai tentar abrir a porta 80 ou 443. Existem algumas formas pra você conseguir "consertar" isso:
> 
> * Colocar um load balancer na frente da sua instancia que aceita conexões na porta 80 e redireciona pra 3333 dessa instancia e configurar ele como um alias dos seus records.
> * Mudar sua aplicação pra rodar na porta 80
> * Colocar um nginx na sua instancia que  aceite conexões na porta 80 e redirecione pra 3333 dele proprio.
> 
> Acho que basicamente existem essas opções, lembre-se que em DNS não se trabalha com porta ou path, para isso você precisa de um servidor web que faça "proxy_pass" e/ou um load balancer, existem diversas formas.

**Comment by fernando10092** [comment]
> Oi Fernando, você não consegue apontar um domínio para uma porta específica, DNSs não funcionam assim. Você tem que ir no registro.br e colocar os Nameservers que a AWS te deu do seu domínio lá. Após isso, você precisa os records A/CNAME para a sua instância, basicamente é um` *.` e um `www`. Mas isso ainda não fará você ver seu aplicativo no seu domínio, pois ele vai tentar abrir a porta 80 ou 443. Existem algumas formas pra você conseguir "consertar" isso:
> 
> * Colocar um load balancer na frente da sua instancia que aceita conexões na porta 80 e redireciona pra 3333 dessa instancia e configurar ele como um alias dos seus records.
> * Mudar sua aplicação pra rodar na porta 80
> * Colocar um nginx na sua instancia que  aceite conexões na porta 80 e redirecione pra 3333 dele proprio.
> 
> Acho que basicamente existem essas opções, lembre-se que em DNS não se trabalha com porta ou path, para isso você precisa de um servidor web que faça "proxy_pass" e/ou um load balancer, existem diversas formas.

@JuanFontes obrigado pela ajuda e pelo seu tempo. Eu sou leigo nesta parte de hospedagem e domínio. Mudei a porta do meu programa e não funcionou. AS outras opções que voce me deu eu não consegui fazer, procurei ajuda no youtube e tudo mais. Voce sabe se há algum video que explique o passo-a-passo ? Eu passeia noite toda ontem tentando pelo Load Balancer mas não consegui.

**Comment by JuanFontes** [comment]
Me chama no telegram, @fernando10092 . É o mesmo usuário do github, posso te ajudar por lá.
